### ISSUE TITLE
[Feature Request] Font size control, dynamic size 

### ISSUE THREAD

**Issue by m-awadi** [liefery/android-stop-badge#18]
Please add attribute to control text size e.g 
```
  <com.liefery.android.icon_badge.IconBadgeView
                android:layout_width="50dp"
                android:layout_height="50dp"
                app:iconBadge_backgroundShapeColor="#bc477b"
                app:iconBadge_stopNumber="11"
 app:textSize="10sp"
  
                app:iconBadge_foregroundShapeColor="#560027" />
```

, and please handle auto resizing "wrap_content" for IconBadgeView that doesn't have fixed size yet e.g 
```
  <com.liefery.android.icon_badge.IconBadgeView
                android:layout_width="wrap_content"
                android:layout_height="50dp"
                app:iconBadge_backgroundShapeColor="#bc477b"
                app:iconBadge_stopNumber="11"
                app:iconBadge_foregroundShapeColor="#560027" />
```
in appove scenario it will never show up

**Comment by taig** [comment]
The text size should be automatically scaled depending on the badge size. Are you seeing scenarios where this behavior breaks?

The missing of `wrap_content` support is due to development lazyness and the fact that the user is _supposed_ to always use square view dimensions.
